[versions]
# Annotations
findbugs = "3.0.2"

# Gradle plugins
spotless = "8.1.0"
publish = "0.35.0"

[libraries]
# Annotations
findbugs = { group = "com.google.code.findbugs", name = "jsr305", version.ref = "findbugs" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
