[versions]
# Annotations
findbugs = "3.0.2"

# Gradle plugins
spotless = "7.0.2"
nexus = "2.0.0"

[libraries]
# Annotations
findbugs = { group = "com.google.code.findbugs", name = "jsr305", version.ref = "findbugs" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
nexus = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus" }
